name: Blazor.Extensions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build

#    - name: Ensure that Playwright is installed
#      run: npx playwright install --with-deps
#    - name: Ensure that Playwright is installed
#      run: sudo pwsh Blazor.Extensions.App.Server.Tests/bin/${{ matrix.configuration }}/net9.0/playwright.ps1 install

    - name: Execute unit tests (Blazor.Extensions.Application.Shared.Tests)
      run: dotnet test Blazor.Extensions.Application.Shared.Tests/Blazor.Extensions.Application.Shared.Tests.csproj

    - name: Execute unit tests (Blazor.Extensions.Application.Tests)
      run: dotnet test Blazor.Extensions.Application.Tests/Blazor.Extensions.Application.Tests.csproj

    - name: Execute unit tests (Blazor.Extensions.Domain.Tests)
      run: dotnet test Blazor.Extensions.Domain.Tests/Blazor.Extensions.Domain.Tests.csproj

    - name: Execute unit tests (Blazor.Extensions.Presentation.Tests)
      run: dotnet test Blazor.Extensions.Presentation.Tests/Blazor.Extensions.Presentation.Tests.csproj

    - name: Execute unit tests (Blazor.Extensions.Infrastructure.Tests)
      run: dotnet test Blazor.Extensions.Infrastructure.Tests/Blazor.Extensions.Infrastructure.Tests.csproj
