name: Blazor.Extensions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Script
      working-directory: Blazor.Extensions.App.Server.Tests/bin/${{ matrix.configuration }}/net9.0
      run: playwright.ps install
      shell: pwsh
    - name: Execute unit tests
      run: dotnet test